//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheNight_JustBuy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int AddressID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string AddressDetail { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string ZipCode { get; set; }
    
        public virtual User User { get; set; }
    }
}
