//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheNight_JustBuy.Models
{
    using System;
    using System.Collections.Generic;
    using TheNight_JustBuy.Areas.Admin.Models;

    public partial class Blog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Blog()
        {
            this.BlogComments = new HashSet<BlogComment>();
        }

        public Blog(BlogModelForCreate blog)
        {
            this.BlogID = blog.BlogID;
            this.BlogName = blog.BlogName;
            this.UserID = blog.UserID;
            this.CategoryID = blog.CategoryID;
            this.ShortDescription = blog.ShortDescription;
            this.Content = blog.Content;
            this.Thumbnail = blog.Thumbnail;
            this.CreatedDate = blog.CreatedDate;
            this.Status = blog.Status;
            
        }

        public int BlogID { get; set; }
        public string BlogName { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string ShortDescription { get; set; }
        public string Content { get; set; }
        public string Thumbnail { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual BlogCategory BlogCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlogComment> BlogComments { get; set; }
        public virtual User User { get; set; }
    }
}
