//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheNight_JustBuy.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class BlogComment
    {
        [DisplayName("Comment ID")]
        public int CommentID { get; set; }
        [DisplayName("User ID")]
        public Nullable<int> UserID { get; set; }
        [DisplayName("Blog ID")]
        public Nullable<int> BlogID { get; set; }
        public string Content { get; set; }
        [DisplayName("Created Date")]
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Blog Blog { get; set; }
        public virtual User User { get; set; }
    }
}
