//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheNight_JustBuy.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    using TheNight_JustBuy.Areas.Admin.Models;

    public partial class Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category()
        {
            this.Products = new HashSet<Product>();
        }

        public Category(CategoryModelForCreate category)
        {
            this.CategoryID = category.CategoryID;
            this.CategoryName = category.CategoryName;
            this.CategoryImage = category.CategoryImage;
        }

        [DisplayName("Category ID")]
        public int CategoryID { get; set; }



        [DisplayName("Category Name")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter a valid category name!")]
        [StringLength(maximumLength: 50, MinimumLength = 3, ErrorMessage = "The category name must be between 3 and 50 characters long.")]
        public string CategoryName { get; set; }

        [DisplayName("Image")]
        public string CategoryImage { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}
