//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheNight_JustBuy.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class ProductImage
    {
        [DisplayName("Image ID")]
        public int ImageID { get; set; }
        [DisplayName("Image")]
        public string ImageFileName { get; set; }
        [DisplayName("Product ID")]
        public Nullable<int> ProductID { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
