//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheNight_JustBuy.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    using TheNight_JustBuy.Areas.Admin.Models;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.ProductComments = new HashSet<ProductComment>();
            this.ProductImages = new HashSet<ProductImage>();
        }

        public Product(ProductModelForCreate product)
        {
            this.ProductID = product.ProductID;
            this.ProductName = product.ProductName;
            this.UnitPrice = product.UnitPrice;
            this.OldUnitPrice = product.OldUnitPrice;
            this.ShortDescription = product.ShortDescription;
            this.Description = product.Description;
            this.Thumbnail = product.Thumbnail;
            this.UnitsInStock = product.UnitsInStock;
            this.LaunchDate = product.LaunchDate;
            this.VotedAverageMark = product.VotedAverageMark;
            this.SupplierID = product.SupplierID;
            this.CategoryID = product.CategoryID;
            this.Status = product.Status;
        }

     
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> UnitPrice { get; set; }
        public Nullable<int> OldUnitPrice { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public string Thumbnail { get; set; }
        public Nullable<int> UnitsInStock { get; set; }
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-ddTHH:mm:ss}")]
        public Nullable<System.DateTime> LaunchDate { get; set; }
        public Nullable<int> VotedAverageMark { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<bool> Status { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }

        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductComment> ProductComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductImage> ProductImages { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
